let dapRecorder, dapPlayer;
window.dapOverlay = new DAPOverlay();

function runtimeMessage(message) { return new Promise(resolve => chrome.runtime.sendMessage(message, response => resolve(response || { ok: false, error: chrome.runtime.lastError?.message || 'No response.' }))); }
function validateWorkflow(workflow) { if (!workflow || typeof workflow !== 'object') return 'Workflow must be a JSON object.'; if (!workflow.workflowId || !workflow.workflowName || !workflow.targetUrlPattern || !Array.isArray(workflow.steps)) return 'Workflow is missing required fields.'; const actions = ['click', 'input', 'select', 'hover', 'verify']; if (workflow.steps.some((step, index) => !step || step.stepIndex !== index + 1 || !actions.includes(step.actionType) || !step.instruction || !step.elementFingerprint?.tagName || !step.elementFingerprint?.cssFallback)) return 'Workflow contains an invalid step.'; return null; }
function setWorkflow(workflow, message = 'Workflow loaded.') { window.dapOverlay.populateWorkflow(workflow); window.dapOverlay.setRecordStatus(message); }
async function refreshSidebar() { const { workflow, storage } = await chrome.storage.local.get(['workflow', 'storage']); if (workflow) setWorkflow(workflow, 'Saved workflow loaded.'); window.dapOverlay.setStorageFields(storage); }
function showHome() { window.dapOverlay.showHome(startRecording, playSavedWorkflow); refreshSidebar(); }
function startRecording() { handleCommand({ type: 'DAP_START_RECORDING' }); }
function stopRecording() { handleCommand({ type: 'DAP_STOP_RECORDING' }); }
async function playSavedWorkflow() { const { workflow } = await chrome.storage.local.get('workflow'); if (!workflow) { window.dapOverlay.show('No saved workflow is available yet.', 'Back to Record', showHome); return; } handleCommand({ type: 'DAP_START_PLAYER', workflow }); }
function exportWorkflow() { chrome.storage.local.get('workflow').then(({ workflow }) => { if (!workflow) return window.dapOverlay.setRecordStatus('No workflow saved.'); const blob = new Blob([JSON.stringify(workflow, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${String(workflow.workflowName || 'guided-workflow').replace(/[^a-z0-9_-]+/gi, '-')}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); window.dapOverlay.setRecordStatus('Workflow exported to Downloads.'); }); }
function importWorkflow(file) { if (!file) return; const reader = new FileReader(); reader.onload = async event => { try { const workflow = JSON.parse(event.target.result); const error = validateWorkflow(workflow); if (error) throw new Error(error); const result = await runtimeMessage({ type: 'WORKFLOW_SAVE', workflow }); if (!result.ok) throw new Error(result.error || 'Save verification failed.'); setWorkflow(result.workflow, 'Workflow imported and verified.'); } catch (error) { window.dapOverlay.setRecordStatus(`Import failed: ${error.message}`); } }; reader.readAsText(file); }
async function saveEdits() { try { const fields = window.dapOverlay.readWorkflowFields(); const workflow = JSON.parse(fields.json); workflow.workflowName = fields.name || workflow.workflowName; workflow.description = fields.description; const error = validateWorkflow(workflow); if (error) throw new Error(error); const result = await runtimeMessage({ type: 'WORKFLOW_SAVE', workflow }); if (!result.ok) throw new Error(result.error || 'Save verification failed.'); setWorkflow(result.workflow, 'Workflow edits saved and verified.'); } catch (error) { window.dapOverlay.setRecordStatus(`Save failed: ${error.message}`); } }
async function saveStorageConfig() { const config = window.dapOverlay.getStorageFields(); if (config.provider !== 'local' && !/^https:\/\//i.test(config.endpoint)) return window.dapOverlay.setRecordStatus('Use an HTTPS gateway endpoint for remote storage.'); const result = await runtimeMessage({ type: 'STORAGE_CONFIG_SAVE', config }); window.dapOverlay.setRecordStatus(result.ok ? 'Storage settings saved.' : result.error || 'Storage settings failed.'); }
async function loadRemoteWorkflow() { const url = window.dapOverlay.getRemoteUrl(); if (!/^https:\/\//i.test(url)) return window.dapOverlay.setRecordStatus('Enter an HTTPS workflow URL.'); const result = await runtimeMessage({ type: 'LOAD_WORKFLOW_URL', url }); if (!result.ok) return window.dapOverlay.setRecordStatus(result.error || 'Unable to load workflow.'); setWorkflow(result.workflow, 'Remote workflow loaded and verified.'); }
async function saveRemoteWorkflow() { const { workflow } = await chrome.storage.local.get('workflow'); if (!workflow) return window.dapOverlay.setRecordStatus('No workflow saved.'); const result = await runtimeMessage({ type: 'WORKFLOW_SAVE_REMOTE', workflow }); window.dapOverlay.setRecordStatus(result.ok ? 'Workflow saved remotely and locally.' : result.error || 'Remote save failed.'); }
function showRecording() { window.dapOverlay.recordAction.textContent = 'Stop recording'; window.dapOverlay.recordAction.onclick = stopRecording; window.dapOverlay.recordMessage.textContent = 'Recording is active. Perform the workflow, then stop recording here.'; window.dapOverlay.setRecordStatus('Recording…'); }
function handleCommand(message) {
  if (!message) return;
  if (message.type === 'DAP_START_RECORDING') { dapRecorder = new DAPRecorder(); dapRecorder.start(); chrome.runtime.sendMessage({ type: 'RECORDING_STATUS', active: true }); showRecording(); }
  if (message.type === 'DAP_STOP_RECORDING') { const workflow = { workflowId: crypto.randomUUID(), workflowName: 'New workflow', targetUrlPattern: location.origin + '/*', steps: dapRecorder?.stop() || [] }; chrome.runtime.sendMessage({ type: 'RECORDING_STATUS', active: false }); runtimeMessage({ type: 'RECORDING_COMPLETE', workflow }).then(result => setWorkflow(result.workflow || workflow, result.ok ? 'Recording saved and verified.' : result.error || 'Recording created but save verification failed.')); window.postMessage({ type: 'DAP_RECORDING_COMPLETE', workflow }, '*'); window.dapOverlay.showHome(startRecording, playSavedWorkflow); }
  if (message.type === 'DAP_START_PLAYER' && message.workflow) { dapPlayer = new DAPPlayer(message.workflow, window.dapOverlay); dapPlayer.start(); }
}
window.dapOverlay.bindControls({ onRecord: startRecording, onPlay: playSavedWorkflow, onExport: exportWorkflow, onImport: importWorkflow, onSave: saveEdits, onSaveConfig: saveStorageConfig, onLoadRemote: loadRemoteWorkflow, onSaveRemote: saveRemoteWorkflow });
window.addEventListener('message', event => { if (event.source === window) handleCommand(event.data); });
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => { handleCommand(message); sendResponse({ ok: true }); });
showHome();
