class DAPPlayer {
  constructor(workflow, overlay = window.dapOverlay || new DAPOverlay()) { this.w = workflow; this.i = 0; this.overlay = overlay; this.activeElement = null; this.inputTimer = null; this.valueWatcher = null; this.advancing = false; this.enter = this.handleEnter.bind(this); this.input = this.handleInput.bind(this); this.click = this.handleClick.bind(this); this.documentClick = this.handleDocumentClick.bind(this); }
  async start() { await this.next(); }
  readValue(element) { return element?.value !== undefined ? String(element.value).trim() : String(element?.innerText || element?.textContent || '').trim(); }
  cleanupElement() { if (this.inputTimer) clearTimeout(this.inputTimer); if (this.valueWatcher) clearInterval(this.valueWatcher); document.removeEventListener('click', this.documentClick, true); if (this.activeElement) { this.activeElement.removeEventListener('keydown', this.enter, true); this.activeElement.removeEventListener('input', this.input, true); this.activeElement.removeEventListener('change', this.input, true); this.activeElement.removeEventListener('click', this.click, true); } this.activeElement = null; this.inputTimer = null; this.valueWatcher = null; this.advancing = false; }
  handleEnter(event) { if (event.key !== 'Enter' || event.shiftKey) return; event.preventDefault(); this.advance(); }
  handleClick(event) { if (event.button !== undefined && event.button !== 0) return; this.advance(); }
  findCalendarSurface() { const selectors = ['[role="dialog"]', '[role="grid"]', '[role="application"]', '.datepicker', '.date-picker', '.calendar', '[class*="calendar"]', '[class*="datepicker"]']; for (const selector of selectors) { const candidates = [...document.querySelectorAll(selector)].filter(element => DAPResolver.isVisible(element)); if (candidates.length) return candidates[candidates.length - 1]; } return null; }
  handleDocumentClick() { if (!this.activeElement) return; const type = String(this.activeElement.type || '').toLowerCase(); const step = this.w.steps[this.i]; if (step?.actionType === 'select' || type === 'date') { if (type === 'date') setTimeout(() => { const calendar = this.findCalendarSurface(); if (calendar) this.overlay.focusTarget(calendar); }, 80); this.queueAdvance(120); } }
  handleInput(event) { if (!this.activeElement) return; if (event.type === 'change' || ['select', 'date'].includes(String(this.activeElement.type || '').toLowerCase()) || String(this.activeElement.tagName).toLowerCase() === 'select') { this.queueAdvance(40); return; } if (this.inputTimer) clearTimeout(this.inputTimer); this.inputTimer = setTimeout(() => this.advance(), 900); }
  queueAdvance(delay = 0) { if (this.inputTimer) clearTimeout(this.inputTimer); this.inputTimer = setTimeout(() => this.advance(), delay); }
  async advance() { if (this.advancing) return; const step = this.w.steps[this.i], element = this.activeElement; if (!step || !element) return; const isDate = String(element.type || '').toLowerCase() === 'date'; const validationStep = isDate ? { ...step, validation: { ...(step.validation || {}), rule: 'not_empty' } } : step; const validation = DAPValidator.validate(validationStep, element); if (!validation.valid) { if (!['input', 'select'].includes(step.actionType)) this.overlay.show(validation.message, 'Try again', () => this.advance(), element); return; } this.advancing = true; this.cleanupElement(); this.i += 1; await this.next(); }
  watchForSelection(step, element) { const initial = this.readValue(element); this.valueWatcher = setInterval(() => { if (!this.activeElement || this.readValue(this.activeElement) === initial || !this.readValue(this.activeElement)) return; this.advance(); }, 150); }
  async next() {
    this.cleanupElement();
    if (this.i >= this.w.steps.length) { this.overlay.show('Workflow complete. The Guided bar will remain available.', 'Back to start', () => this.overlay.showHome()); return; }
    const step = this.w.steps[this.i]; const element = await DAPResolver.waitForElement(step.elementFingerprint).catch(() => null);
    if (!element) { this.overlay.show(`Step ${this.i + 1} could not find its target.`, 'Back to start', () => this.overlay.showHome()); return; }
    const tag = String(element.tagName || '').toLowerCase(); const nextStep = this.w.steps[this.i + 1];
    if (step.actionType === 'click' && ['input', 'textarea', 'select'].includes(tag) && nextStep && ['input', 'select'].includes(nextStep.actionType)) { this.i += 1; await this.next(); return; }
    this.activeElement = element; const isDate = String(element.type || '').toLowerCase() === 'date';
    try { if (isDate && (step.injectData || step.validation?.rule === 'exact_match')) DAPInjector.applyInput(element, ''); if (step.autoPilot && step.injectData && !isDate) DAPInjector.applyInput(element, DAPInjector.resolveValue(step.injectData, this.w.globalInjections)); } catch (error) { this.overlay.show(`Guided could not prepare this field: ${error.message}`, 'Retry', () => this.next(), element); return; }
    if (step.actionType === 'click') { element.addEventListener('click', this.click, true); this.overlay.show(`Step ${this.i + 1} of ${this.w.steps.length}: ${step.instruction}`, 'Continue', () => this.advance(), element); return; }
    if (['input', 'select'].includes(step.actionType)) { element.addEventListener('keydown', this.enter, true); element.addEventListener('input', this.input, true); element.addEventListener('change', this.input, true); element.focus?.(); if (step.actionType === 'select' || isDate) { this.watchForSelection(step, element); document.addEventListener('click', this.documentClick, true); } this.overlay.show(`Step ${this.i + 1} of ${this.w.steps.length}: ${step.instruction}`, 'Continue', () => this.advance(), element); return; }
    element.addEventListener('keydown', this.enter, true); element.focus?.(); this.overlay.show(`Step ${this.i + 1} of ${this.w.steps.length}: ${step.instruction}`, 'Continue', () => this.advance(), element);
  }
}
window.DAPPlayer = DAPPlayer;
