class DAPRecorder {
  constructor() { this.isRecording = false; this.recordedSteps = []; this.click = this.handleClick.bind(this); this.change = this.handleInput.bind(this); }
  start() { if (this.isRecording) return; this.isRecording = true; this.recordedSteps = []; document.addEventListener('click', this.click, true); document.addEventListener('change', this.change, true); }
  stop() { if (!this.isRecording) return this.recordedSteps; this.isRecording = false; document.removeEventListener('click', this.click, true); document.removeEventListener('change', this.change, true); return this.recordedSteps; }
  generateFingerprint(el) { const id = el.id && !/(:\w+:|\d{4,}|ember|react|ng-)/i.test(el.id) ? el.id : null; return { tagName: String(el.tagName || 'div').toLowerCase(), id, testId: el.getAttribute('data-testid') || el.getAttribute('data-qa') || el.getAttribute('data-cy') || null, name: el.getAttribute('name') || null, type: el.getAttribute('type') || null, role: el.getAttribute('role') || null, ariaLabel: el.getAttribute('aria-label') || null, placeholder: el.getAttribute('placeholder') || null, title: el.getAttribute('title') || null, alt: el.getAttribute('alt') || null, value: el.getAttribute('value') || null, labelText: this.label(el), innerTextSnippet: String(el.innerText || el.textContent || '').trim().slice(0, 80) || null, cssFallback: this.css(el) }; }
  label(el) { if (el.id) { const label = document.querySelector(`label[for="${CSS.escape(el.id)}"]`); if (label) return String(label.innerText || label.textContent || '').trim(); } const parent = el.closest?.('label'); return parent ? String(parent.innerText || parent.textContent || '').trim() : null; }
  css(el) { if (el.id) return `#${CSS.escape(el.id)}`; const path = []; for (let current = el; current && current !== document.body; current = current.parentElement) { const tag = String(current.tagName || 'div').toLowerCase(); const stable = current.getAttribute?.('data-testid') || current.getAttribute?.('data-qa') || current.getAttribute?.('data-cy'); if (stable) { path.unshift(`[data-testid="${CSS.escape(stable)}"]`); break; } path.unshift(tag); } return path.join(' > ') || String(el.tagName || 'div').toLowerCase(); }
  handleClick(e) { const el = e.target; if (!this.isRecording || !el || el.closest?.('#dap-extension-host')) return; this.add('click', el, `Click on ${(el.innerText || el.textContent || el.tagName || 'element').trim().slice(0, 40)}.`); }
  handleInput(e) { const el = e.target; if (!this.isRecording || !el || el.closest?.('#dap-extension-host')) return; this.add('input', el, `Enter a value in ${this.label(el) || el.name || 'this field'}.`, el.value ?? ''); }
  add(actionType, el, instruction, injectData = '') { const step = { stepIndex: this.recordedSteps.length + 1, actionType, instruction, elementFingerprint: this.generateFingerprint(el), injectData, autoPilot: false, validation: actionType === 'input' ? { rule: 'not_empty', errorMessage: 'This field cannot be empty.' } : { rule: 'element_exists', errorMessage: 'Required element is not present.' } }; this.recordedSteps.push(step); window.postMessage({ type: 'DAP_STEP_RECORDED', step }, '*'); }
}
window.DAPRecorder = DAPRecorder;
