class DAPRecorder {
  constructor() { this.isRecording = false; this.recordedSteps = []; this.recordedInputs = new WeakSet(); this.click = this.handleClick.bind(this); this.change = this.handleInput.bind(this); this.keydown = this.handleKeydown.bind(this); }
  start() { if (this.isRecording) return; this.isRecording = true; this.recordedSteps = []; this.recordedInputs = new WeakSet(); document.addEventListener('click', this.click, true); document.addEventListener('change', this.change, true); document.addEventListener('keydown', this.keydown, true); }
  stop() { if (!this.isRecording) return this.recordedSteps; this.isRecording = false; document.removeEventListener('click', this.click, true); document.removeEventListener('change', this.change, true); document.removeEventListener('keydown', this.keydown, true); return this.recordedSteps; }
  isEditable(el) { const tag = String(el?.tagName || '').toLowerCase(); return ['input', 'textarea', 'select'].includes(tag) || el?.isContentEditable || el?.getAttribute?.('contenteditable') === 'true'; }
  isToggle(el) { return String(el?.tagName || '').toLowerCase() === 'input' && ['checkbox', 'radio'].includes(String(el.type || '').toLowerCase()); }
  generateFingerprint(el) { const id = el.id && !/(:\w+:|\d{4,}|ember|react|ng-)/i.test(el.id) ? el.id : null; const type = el.getAttribute('type') || null; const value = type === 'date' ? null : (el.getAttribute('value') || null); return { tagName: String(el.tagName || 'div').toLowerCase(), id, testId: el.getAttribute('data-testid') || el.getAttribute('data-qa') || el.getAttribute('data-cy') || null, name: el.getAttribute('name') || null, type, role: el.getAttribute('role') || null, ariaLabel: el.getAttribute('aria-label') || null, placeholder: el.getAttribute('placeholder') || null, title: el.getAttribute('title') || null, alt: el.getAttribute('alt') || null, value, labelText: this.label(el), innerTextSnippet: String(el.innerText || el.textContent || '').trim().slice(0, 80) || null, cssFallback: this.css(el) }; }
  label(el) { if (el.id) { const label = document.querySelector(`label[for="${CSS.escape(el.id)}"]`); if (label) return String(label.innerText || label.textContent || '').trim(); } const parent = el.closest?.('label'); return parent ? String(parent.innerText || parent.textContent || '').trim() : null; }
  css(el) { if (el.id) return `#${CSS.escape(el.id)}`; const path = []; for (let current = el; current && current !== document.body; current = current.parentElement) { const tag = String(current.tagName || 'div').toLowerCase(); const stable = current.getAttribute?.('data-testid') || current.getAttribute?.('data-qa') || current.getAttribute?.('data-cy'); if (stable) { path.unshift(`[data-testid="${CSS.escape(stable)}"]`); break; } path.unshift(tag); } return path.join(' > ') || String(el.tagName || 'div').toLowerCase(); }
  handleClick(event) { const el = event.target; if (!this.isRecording || !el || el.closest?.('#dap-extension-host') || (this.isEditable(el) && !this.isToggle(el))) return; this.add('click', el, `Click on ${(el.innerText || el.textContent || el.tagName || 'element').trim().slice(0, 40)}.`); }
  handleInput(event) { const el = event.target; if (!this.isRecording || !el || this.recordedInputs.has(el) || el.closest?.('#dap-extension-host') || this.isToggle(el)) return; this.recordedInputs.add(el); const tag = String(el.tagName || '').toLowerCase(); const type = String(el.type || '').toLowerCase(); const isSelect = tag === 'select'; const isDate = type === 'date'; const label = this.label(el) || el.name || 'this field'; this.add(isSelect ? 'select' : 'input', el, isSelect ? `Select an option from ${label}.` : isDate ? `Select a date in ${label}.` : `Enter a value in ${label}.`, isSelect || isDate ? '' : (el.value ?? '')); }
  handleKeydown(event) { const el = event.target; if (!this.isRecording || event.key !== 'Enter' || event.shiftKey || !this.isEditable(el)) return; event.preventDefault(); this.handleInput(event); }
  add(actionType, el, instruction, injectData = '') { const step = { stepIndex: this.recordedSteps.length + 1, actionType, instruction, elementFingerprint: this.generateFingerprint(el), injectData, autoPilot: false, validation: ['input', 'select'].includes(actionType) ? { rule: 'not_empty', errorMessage: actionType === 'select' ? 'Please select an option.' : 'Please complete this field.' } : { rule: 'element_exists', errorMessage: 'Required element is not present.' } }; this.recordedSteps.push(step); window.postMessage({ type: 'DAP_STEP_RECORDED', step }, '*'); }
}
window.DAPRecorder = DAPRecorder;
