const $ = id => document.getElementById(id); const status = text => { $('status').textContent = text; };
let recording = false;
async function tab() { const [active] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!active?.id) throw new Error('No active tab.'); return active; }
function validateWorkflow(w) { if (!w || typeof w !== 'object') return 'Workflow must be a JSON object.'; if (!w.workflowId || !w.workflowName || !w.targetUrlPattern || !Array.isArray(w.steps)) return 'Workflow is missing required fields.'; const actions = ['click', 'input', 'select', 'hover', 'verify']; if (w.steps.some((s, i) => !s || s.stepIndex !== i + 1 || !actions.includes(s.actionType) || !s.instruction || !s.elementFingerprint?.tagName || !s.elementFingerprint?.cssFallback)) return 'Workflow contains an invalid or out-of-order step.'; return null; }
function showWorkflow(w) { $('name').value = w?.workflowName || ''; $('description').value = w?.description || ''; $('editor').value = w ? JSON.stringify(w, null, 2) : ''; }
async function currentWorkflow() { const { workflow } = await chrome.storage.local.get('workflow'); if (!workflow) throw new Error('No workflow saved.'); return workflow; }
async function sendToTab(type, workflow) { const t = await tab(); return new Promise(resolve => chrome.tabs.sendMessage(t.id, { type, workflow }, response => { if (chrome.runtime.lastError) return resolve({ ok: false, error: 'This page does not allow Guided content scripts.' }); resolve(response || { ok: true }); })); }
async function loadStatus() { const r = await chrome.runtime.sendMessage({ type: 'RECORDING_STATUS_GET' }); recording = Boolean(r?.active); $('record').textContent = recording ? 'Stop recording' : 'Start recording'; const { workflow } = await chrome.storage.local.get('workflow'); showWorkflow(workflow); const { storage } = await chrome.storage.local.get('storage'); if (storage) { $('provider').value = storage.provider || 'local'; $('endpoint').value = storage.endpoint || ''; $('bucket').value = storage.bucket || ''; $('container').value = storage.container || ''; $('prefix').value = storage.prefix || ''; } }
$('record').onclick = async () => { try { const type = recording ? 'DAP_STOP_RECORDING' : 'DAP_START_RECORDING'; const result = await sendToTab(type); if (result.ok === false) return status(result.error); recording = !recording; $('record').textContent = recording ? 'Stop recording' : 'Start recording'; status(recording ? 'Recording on this tab…' : 'Recording stopped and saved.'); } catch (e) { status(e.message); } };
$('play').onclick = async () => { try { const workflow = await currentWorkflow(); const result = await sendToTab('DAP_START_PLAYER', workflow); if (result.ok === false) return status(result.error); status('Workflow started.'); } catch (e) { status(e.message); } };
$('export').onclick = async () => { try { const workflow = await currentWorkflow(); const blob = new Blob([JSON.stringify(workflow, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `${String(workflow.workflowName || 'guided-workflow').replace(/[^a-z0-9_-]+/gi, '-')}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); status('Workflow exported to Downloads.'); } catch (e) { status(`Export failed: ${e.message}`); } };
$('loadFile').onclick = () => $('file').click();
$('file').onchange = () => { const file = $('file').files[0]; if (!file) return; const reader = new FileReader(); reader.onload = e => { try { const workflow = JSON.parse(e.target.result); const error = validateWorkflow(workflow); if (error) throw new Error(error); chrome.storage.local.set({ workflow }).then(() => chrome.storage.local.get('workflow')).then(({ workflow: saved }) => { showWorkflow(saved); status(saved?.workflowId === workflow.workflowId ? 'Workflow imported and verified.' : 'Workflow save verification failed.'); }); } catch (e) { status(`Import failed: ${e.message}`); } }; reader.readAsText(file); };
$('save').onclick = async () => { try { const workflow = JSON.parse($('editor').value); workflow.workflowName = $('name').value.trim() || workflow.workflowName; workflow.description = $('description').value.trim(); const error = validateWorkflow(workflow); if (error) throw new Error(error); const result = await chrome.runtime.sendMessage({ type: 'WORKFLOW_SAVE', workflow }); if (!result?.ok) throw new Error(result?.error || 'Save verification failed.'); showWorkflow(result.workflow); status('Workflow edits saved and verified.'); } catch (e) { status(`Save failed: ${e.message}`); } };
$('saveConfig').onclick = async () => { const endpoint = $('endpoint').value.trim(); if ($('provider').value !== 'local' && !/^https:\/\//i.test(endpoint)) return status('Use an HTTPS gateway endpoint for remote storage.'); const result = await chrome.runtime.sendMessage({ type: 'STORAGE_CONFIG_SAVE', config: { provider: $('provider').value, endpoint, bucket: $('bucket').value, container: $('container').value, prefix: $('prefix').value } }); status(result?.ok ? 'Storage settings saved.' : result?.error || 'Storage settings failed.'); };
$('load').onclick = () => { const url = $('url').value.trim(); if (!/^https:\/\//i.test(url)) return status('Enter an HTTPS workflow URL.'); chrome.runtime.sendMessage({ type: 'LOAD_WORKFLOW_URL', url }, r => { if (chrome.runtime.lastError) return status(chrome.runtime.lastError.message); if (!r?.ok) return status(r?.error || 'Unable to load workflow.'); showWorkflow(r.workflow); status('Remote workflow loaded and verified.'); }); };
$('saveRemote').onclick = async () => { try { const workflow = await currentWorkflow(); const result = await chrome.runtime.sendMessage({ type: 'WORKFLOW_SAVE_REMOTE', workflow }); status(result?.ok ? 'Workflow saved remotely and locally.' : result?.error || 'Remote save failed.'); } catch (e) { status(e.message); } };
loadStatus().catch(e => status(e.message));
